# Generated by Django 5.2.4 on 2025-08-25 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('IdParticipant', models.AutoField(primary_key=True, serialize=False)),
                ('Mail', models.CharField(max_length=50)),
                ('Mdp', models.CharField(max_length=6)),
                ('Genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('NumS', models.AutoField(primary_key=True, serialize=False)),
                ('Theme', models.CharField(max_length=50)),
                ('DateDebut', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumQ', models.IntegerField()),
                ('Content', models.CharField(max_length=150)),
                ('NumS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendages.sondage')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rep', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('S', 'Sans avis')], max_length=1)),
                ('IdParticipant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendages.participant')),
                ('NumQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendages.question')),
                ('NumS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendages.sondage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('NumQ', 'NumS', 'IdParticipant'), name='unique_mesure_pk2')],
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('NumQ', 'NumS'), name='unique_mesure_pk'),
        ),
    ]
